//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bombs_H
#define METASPRITE_bombs_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bombs_TILE_ORIGIN 0
#define bombs_TILE_W 8
#define bombs_TILE_H 8
#define bombs_WIDTH 160
#define bombs_HEIGHT 144
#define bombs_TILE_COUNT 113
#define bombs_PALETTE_COUNT 1
#define bombs_COLORS_PER_PALETTE 4
#define bombs_TOTAL_COLORS 4
#define bombs_MAP_ATTRIBUTES 0
extern const unsigned char bombs_map[360];
#define bombs_map_attributes bombs_map

BANKREF_EXTERN(bombs)

extern const palette_color_t bombs_palettes[4];
extern const uint8_t bombs_tiles[1808];

#endif
