//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_door_H
#define METASPRITE_door_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define door_TILE_ORIGIN 0
#define door_TILE_W 8
#define door_TILE_H 8
#define door_WIDTH 160
#define door_HEIGHT 144
#define door_TILE_COUNT 124
#define door_PALETTE_COUNT 1
#define door_COLORS_PER_PALETTE 4
#define door_TOTAL_COLORS 4
#define door_MAP_ATTRIBUTES 0
extern const unsigned char door_map[360];
#define door_map_attributes door_map

BANKREF_EXTERN(door)

extern const palette_color_t door_palettes[4];
extern const uint8_t door_tiles[1984];

#endif
